### ISSUE TITLE
Problem in "Desertscape.make"

### ISSUE THREAD

**Issue by imagine5am** [aparis69/Desertscapes-Simulation#1]
Code requires "heightfield.cpp" file but it is not there. 

LOGS (on running "make" command in G++ folder):

==== Building Desertscape (debug64) ====
Creating obj/x64/Debug
desert-flow.cpp
desert-simulation.cpp
desert.cpp
make[1]: *** No rule to make target '../Code/Source/heightfield.cpp', needed by 'obj/x64/Debug/heightfield.o'.  Stop.
Makefile:16: recipe for target 'Desertscape' failed
make: *** [Desertscape] Error 2

**Comment by aparis69** [comment]
Whoops, Notification was not activated on this repository. Sorry for the response delay!

Issue is now fixed - the makefile was not up to date.
Thank you for reporting this.

Axel
